title: "양재천 수달 보호 단체"
labels: [Discussions]
body:
- type: textarea
  id: Description
  attributes:
    label: Bugs Description
    description: 버그 상황에 대해 자세히 써주세요
    value: |
      버그 발생한 OS
      버그 상황 설명
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: BDD_TASK
  attributes:
    label: BDD TASK
    description: BDD 작성은 given > when > then 순으로 작성해주세요 :)
    value: |
      - [ ] 랜덤 이미지 배경 적용 후 다운로드시 정상적으로 이미지가 보인다.
      ...
      ...
    render: bash
  validations:
    required: true
