on:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: CI='false' npm run build
        working-directory: ${{ env.working-directory }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./frontend/build
