name: eslint check

on:
  push:
    branches:
      - init/auto-lint

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          cd frontend
          npm ci
          npm run lint
        env:
          CI: true
